#---------------------------------------#
stages:
  - build
  - deploy
#---------------------------------------#

#------------Build Template-------------#
.build: &build
  stage: build

  image: docker

  services:
    - name: docker:20-dind
      alias: docker

  before_script:
    - echo "Harbor Login"
    - docker login --username $HARBOR_REGISTRY_USER --password $HARBOR_REGISTRY_USER_PASSWORD $HARBOR_REGISTRY

  script:
    - echo "Dockerfile Build"
    - docker build --no-cache --tag $TAG:$CI_PIPELINE_IID .
    - docker tag $TAG:$CI_PIPELINE_IID $TAG:latest

    - echo "Harbor Push"
    - docker push $TAG:$CI_PIPELINE_IID
    - docker push $TAG:latest

    - echo "Clean"
    - docker rmi --force $(docker images -q "$TAG" | uniq)
    - docker rmi `docker images | grep "<none>" | awk {'print $3'}`

#------------Deploy Template--------------#
.deploy: &deploy
  stage: deploy
  image: alpine
  script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_HOST_SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - ssh-keyscan -t ecdsa 192.168.230.134 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
 
    - ssh spring-demo-user@192.168.230.134 "
      cd spring-docker-project/;
      pwd;
      ./update.sh"
#----------------------------------#
 
#----------Dev Branch--------------#
BuildToDev:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
  except:
    - preprod
    - prod
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    GIT_SSL_NO_VERIFY: "1"
    APP_NAME: spring-app-docker-dev
    TAG: $HARBOR_REGISTRY_TAG/$HARBOR_NAMESPACE/$APP_NAME
  <<: *build
#--
DeployToDev:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
  except:
    - preprod
    - prod
  needs: [BuildToDev]
  <<: *deploy
#--------------------------------------#

#----------Preprod Branch--------------#
BuildToPreprod:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "preprod" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod"
  when: manual
  except:
    - main
    - prod
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    GIT_SSL_NO_VERIFY: "1"
    APP_NAME: spring-app-docker-preprod
    TAG: $HARBOR_REGISTRY_TAG/$HARBOR_NAMESPACE/$APP_NAME
  <<: *build
#--
DeployToPreprod:
  only:
    variables:
      - $CI_COMMIT_BRANCH == "preprod" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod"
  except:
    - main
    - prod
  needs: [BuildToPreprod]
  <<: *deploy
#--------------------------------------#
 
#----------Prod Branch-----------------#
BuildToProd:
  only:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "prod"
  when: manual
  except:
    - main
    - preprod
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    GIT_SSL_NO_VERIFY: "1"
    APP_NAME: spring-app-docker-prod
    TAG: $HARBOR_REGISTRY_TAG/$HARBOR_NAMESPACE/$APP_NAME
  <<: *build
#--
DeployToProd:
  only:
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "prod"
  except:
    - main
    - preprod
  needs: [BuildToProd]
  <<: *deploy
#--------------------------------------#